const crypto=require("node:crypto"),fs=require("node:fs"),http=require("node:http"),path=require("node:path"),Database=require("better-sqlite3");
const dir=path.resolve(process.env.LICENSE_DATA_DIR||path.join(__dirname,"data")),adminDir=path.join(__dirname,"admin");fs.mkdirSync(dir,{recursive:true});
const privatePath=path.join(dir,"private-key.pem"),publicPath=path.join(dir,"public-key.pem");if(!fs.existsSync(privatePath)){const pair=crypto.generateKeyPairSync("ed25519");fs.writeFileSync(privatePath,pair.privateKey.export({type:"pkcs8",format:"pem"}),{mode:0o600});fs.writeFileSync(publicPath,pair.publicKey.export({type:"spki",format:"pem"}));}
const privateKey=fs.readFileSync(privatePath,"utf8"),publicKey=fs.readFileSync(publicPath,"utf8"),db=new Database(path.join(dir,"licenses.sqlite"));db.pragma("journal_mode = WAL");db.exec(`CREATE TABLE IF NOT EXISTS licenses(id TEXT PRIMARY KEY,key_hash TEXT UNIQUE NOT NULL,key_hint TEXT NOT NULL DEFAULT '',product TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'active',expires_at TEXT NOT NULL,max_devices INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL);CREATE TABLE IF NOT EXISTS devices(license_id TEXT NOT NULL,device_id TEXT NOT NULL,activated_at TEXT NOT NULL,last_seen_at TEXT NOT NULL,revoked_at TEXT,PRIMARY KEY(license_id,device_id));`);try{db.exec("ALTER TABLE licenses ADD COLUMN key_hint TEXT NOT NULL DEFAULT ''")}catch{}
const hash=x=>crypto.createHash("sha256").update(String(x)).digest("hex"),send=(res,status,value,headers={})=>{res.writeHead(status,{"content-type":"application/json; charset=utf-8","cache-control":"no-store",...headers});res.end(JSON.stringify(value));},adminOk=req=>{const expected=String(process.env.LICENSE_ADMIN_TOKEN||""),actual=String(req.headers.authorization||"").replace(/^Bearer\s+/i,"");return expected.length>=16&&actual.length===expected.length&&crypto.timingSafeEqual(Buffer.from(actual),Buffer.from(expected));};
async function body(req){const parts=[];let size=0;for await(const p of req){size+=p.length;if(size>65536)throw new Error("request_too_large");parts.push(p)}return JSON.parse(Buffer.concat(parts).toString("utf8")||"{}");}
function token(row,deviceId){const now=Date.now(),offline=Math.min(Date.parse(row.expires_at),now+7*86400000),payload=Buffer.from(JSON.stringify({licenseId:row.id,product:row.product,deviceId,issuedAt:new Date(now).toISOString(),expiresAt:row.expires_at,offlineUntil:new Date(offline).toISOString()})).toString("base64url");return `${payload}.${crypto.sign(null,Buffer.from(payload),privateKey).toString("base64url")}`;}
function adminList(){return db.prepare(`SELECT l.id,l.key_hint keyHint,l.product,l.status,l.expires_at expiresAt,l.max_devices maxDevices,l.created_at createdAt,COUNT(CASE WHEN d.revoked_at IS NULL THEN 1 END) activeDevices FROM licenses l LEFT JOIN devices d ON d.license_id=l.id GROUP BY l.id ORDER BY l.created_at DESC`).all();}
function serveAdmin(res,url){const file=url==="/admin/app.js"?"app.js":url==="/admin/style.css"?"style.css":"index.html",type=file.endsWith(".js")?"text/javascript; charset=utf-8":file.endsWith(".css")?"text/css; charset=utf-8":"text/html; charset=utf-8",target=path.join(adminDir,file);if(!fs.existsSync(target))return send(res,404,{error:"not_found"});res.writeHead(200,{"content-type":type,"cache-control":"no-store","x-content-type-options":"nosniff"});fs.createReadStream(target).pipe(res);}
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,"http://localhost");if(req.method==="GET"&&(url.pathname==="/admin"||url.pathname.startsWith("/admin/")))return serveAdmin(res,url.pathname);if(req.method==="GET"&&url.pathname==="/health")return send(res,200,{ok:true});if(url.pathname.startsWith("/v1/admin/")&&!adminOk(req))return send(res,401,{error:"unauthorized"});
if(req.method==="GET"&&url.pathname==="/v1/admin/licenses")return send(res,200,{items:adminList()});
if(req.method==="GET"&&url.pathname.match(/^\/v1\/admin\/licenses\/[^/]+\/devices$/)){const id=url.pathname.split("/")[4],items=db.prepare("SELECT device_id deviceId,activated_at activatedAt,last_seen_at lastSeenAt,revoked_at revokedAt FROM devices WHERE license_id=? ORDER BY activated_at DESC").all(id);return send(res,200,{items});}
if(req.method!=="POST")return send(res,404,{error:"not_found"});const input=await body(req);
if(url.pathname==="/v1/admin/licenses"){const key=crypto.randomBytes(18).toString("base64url"),id=crypto.randomUUID(),expires=new Date(input.expiresAt||Date.now()+365*86400000);if(!Number.isFinite(expires.getTime())||expires<=new Date())return send(res,400,{error:"invalid_expiry"});db.prepare("INSERT INTO licenses(id,key_hash,key_hint,product,status,expires_at,max_devices,created_at) VALUES (?,?,?,?,?,?,?,?)").run(id,hash(key),`${key.slice(0,4)}…${key.slice(-4)}`,input.product||"configurable-api","active",expires.toISOString(),Math.max(1,Math.min(100,Number(input.maxDevices)||1)),new Date().toISOString());return send(res,201,{id,licenseKey:key,expiresAt:expires.toISOString()});}
let match=url.pathname.match(/^\/v1\/admin\/licenses\/([^/]+)\/status$/);if(match){const status=input.status==="active"?"active":"disabled";if(!db.prepare("UPDATE licenses SET status=? WHERE id=?").run(status,match[1]).changes)return send(res,404,{error:"not_found"});return send(res,200,{ok:true,status});}
match=url.pathname.match(/^\/v1\/admin\/licenses\/([^/]+)\/devices\/([^/]+)\/revoke$/);if(match){db.prepare("UPDATE devices SET revoked_at=? WHERE license_id=? AND device_id=?").run(new Date().toISOString(),match[1],decodeURIComponent(match[2]));return send(res,200,{ok:true});}
if(url.pathname==="/v1/licenses/activate"){const row=db.prepare("SELECT * FROM licenses WHERE key_hash=? AND product=?").get(hash(input.licenseKey),input.product);if(!row||row.status!=="active"||Date.parse(row.expires_at)<=Date.now())return send(res,403,{error:"invalid_license"});const existing=db.prepare("SELECT * FROM devices WHERE license_id=? AND device_id=? AND revoked_at IS NULL").get(row.id,input.deviceId),count=db.prepare("SELECT COUNT(*) count FROM devices WHERE license_id=? AND revoked_at IS NULL").get(row.id).count;if(!existing&&count>=row.max_devices)return send(res,409,{error:"device_limit_reached"});const now=new Date().toISOString();db.prepare("INSERT INTO devices VALUES (?,?,?,?,NULL) ON CONFLICT(license_id,device_id) DO UPDATE SET last_seen_at=excluded.last_seen_at,revoked_at=NULL").run(row.id,input.deviceId,now,now);return send(res,200,{token:token(row,input.deviceId)});}
if(url.pathname==="/v1/licenses/validate"){const [p,s]=String(input.token||"").split(".");if(!p||!s||!crypto.verify(null,Buffer.from(p),publicKey,Buffer.from(s,"base64url")))return send(res,403,{error:"invalid_token"});const claim=JSON.parse(Buffer.from(p,"base64url").toString());if(claim.deviceId!==input.deviceId||claim.product!==input.product)return send(res,403,{error:"token_mismatch"});const row=db.prepare("SELECT * FROM licenses WHERE id=? AND product=?").get(claim.licenseId,input.product),device=row&&db.prepare("SELECT * FROM devices WHERE license_id=? AND device_id=? AND revoked_at IS NULL").get(row.id,input.deviceId);if(!row||!device||row.status!=="active"||Date.parse(row.expires_at)<=Date.now())return send(res,403,{error:"license_revoked_or_expired"});db.prepare("UPDATE devices SET last_seen_at=? WHERE license_id=? AND device_id=?").run(new Date().toISOString(),row.id,input.deviceId);return send(res,200,{token:token(row,input.deviceId)});}return send(res,404,{error:"not_found"});}catch(error){return send(res,400,{error:error.message});}});
server.listen(Number(process.env.PORT)||8787,process.env.HOST||"127.0.0.1",()=>console.log(`License server: http://${process.env.HOST||"127.0.0.1"}:${Number(process.env.PORT)||8787}\nAdmin: /admin\nPublic key: ${publicPath}`));
